pipeline
{
  agent any
  stages
  {
    stage("GIT")
    {
      steps
      {
        git "https://github.com/amanbaghel101/feature.git"
      }
    }
    stage("Run")
    {
      steps
      {
        bat "sh shell.sh"
      }
    }
  }
}
